name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install & Build
        run: |
          bun install
          bun run build
          
          # Fix for TanStack Start: Move hidden client files to the surface
          if [ -d "./dist/client" ]; then cp -r ./dist/client/* ./dist/; fi
          if [ -f "./dist/_shell.html" ] && [ ! -f "./dist/index.html" ]; then mv ./dist/_shell.html ./dist/index.html; fi
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
